name: Update Date Field in Project

on:
  issues:
    types: [edited]

jobs:
  update-date-field:
    runs-on: ubuntu-latest
    steps:
      - name: Check if field is changed
        if: github.event.changes.body != null && contains(github.event.changes.body.from, 'specific_field_value')
        run: |
          # Get the issue or pull request number
          number=$(jq --raw-output .issue.number <<< "$GITHUB_EVENT_PATH")
          
          # Get the current date
          current_date=$(date +%Y-%m-%d)
          
          # Update the project card's date field
          curl \
            -X POST \
            -H "Accept: application/vnd.github.inertia-preview+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/projects/columns/<COLUMN_ID>/cards \
            -d "{\"content_id\": $number, \"content_type\": \"Issue\", \"note\": \"Updated date field: $current_date\"}"
